//DO NOT MODIFY generated by the tse script.
import { styleFactory, themeClass} from "ts-emeth";
    
export {adopt} from "ts-emeth";

export enum CompCssStyles {
  "container" = "container",
  "border" = "border",
  "hello" = "hello",
  "to-camel" = "to-camel",
  "toCamel" = "toCamel",
}

export const CssStyles = CompCssStyles;

export default styleFactory(themeClass({displayName: "Comp"}), CssStyles);

