//DO NOT MODIFY generated by the tse script.
import { styleFactory, themeClass} from "ts-emeth";
    
export {adopt} from "ts-emeth";

export enum OtherCssStyles {
  "container" = "container",
  "header" = "header",
  "more" = "more",
  "comp" = "comp",
}

export const CssStyles = OtherCssStyles;

export default styleFactory(themeClass({displayName: "Other"}), CssStyles);

