import {fileToClassName} from "./util";

export default (filePath, keys, shasum = '') => {
    const clazz = fileToClassName(filePath);

    return `//DO NOT MODIFY generated by the tse script. -- {${shasum}} 
import { styleFactory, themeClass} from "ts-emeth";
    
export {adopt} from "ts-emeth";

export enum ${clazz}CssStyles {
${keys.map(line => `  ${JSON.stringify(line)} = ${JSON.stringify(line)}`).join(`,\n`)},
}

export const CssStyles = ${clazz}CssStyles;

export default styleFactory(themeClass({displayName: "${clazz}"}), CssStyles);

`;
}
